import Image from "next/image";

export default function StockHeader() {
  const company = {
    Symbol: "IBM",
    AssetType: "Common Stock",
    Name: "International Business Machines",
    Description:
      "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
    CIK: "51143",
    Exchange: "NYSE",
    Currency: "USD",
    Country: "USA",
    Sector: "TECHNOLOGY",
    Industry: "COMPUTER & OFFICE EQUIPMENT",
    Address: "1 NEW ORCHARD ROAD, ARMONK, NY, US",
    FiscalYearEnd: "December",
    LatestQuarter: "2023-06-30",
    MarketCapitalization: "125727932000",
    EBITDA: "12985000000",
    PERatio: "58.73",
    PEGRatio: "1.276",
    BookValue: "24.37",
    DividendPerShare: "6.61",
    DividendYield: "0.0481",
    EPS: "2.35",
    RevenuePerShareTTM: "66.75",
    ProfitMargin: "0.0335",
    OperatingMarginTTM: "0.141",
    ReturnOnAssetsTTM: "0.0411",
    ReturnOnEquityTTM: "0.104",
    RevenueTTM: "60524999000",
    GrossProfitTTM: "32688000000",
    DilutedEPSTTM: "2.35",
    QuarterlyEarningsGrowthYOY: "0.126",
    QuarterlyRevenueGrowthYOY: "-0.004",
    AnalystTargetPrice: "146",
    TrailingPE: "58.73",
    ForwardPE: "15.55",
    PriceToSalesRatioTTM: "2.108",
    PriceToBookRatio: "6.75",
    EVToRevenue: "2.969",
    EVToEBITDA: "25.81",
    Beta: "0.771",
    "52WeekHigh": "151.93",
    "52WeekLow": "118.71",
    "50DayMovingAverage": "143.8",
    "200DayMovingAverage": "135.44",
    SharesOutstanding: "911006000",
    DividendDate: "2023-09-09",
    ExDividendDate: "2023-08-09",
  };
  const price = "$567.32";
  const high = "+6.71";
  const isGainer = true;
  
  return (
    <div className="flex justify-between">
      <div className="flex gap-3 md:gap-8">
        <div
          className={`flex justify-center items-center px-9 rounded-full bg-gradient-to-r from-[#90EE91] to-[#BFF4BE]`}
        >
          <h1 className={`text-xl font-bold text-[#097969]`}>
            {company.Symbol[0]}
          </h1>
        </div>
        <div>
          <h1 className="text-lg font-semibold">{company.Name}</h1>
          <p className="text-gray-700 font-semibold">
            {company.Symbol}, {company.AssetType}
          </p>
          <p className="text-gray-400 font-semibold">{company.Exchange}</p>
        </div>
      </div>
      <div className="flex flex-col justify-center">
        <p className="font-bold">{price}</p>
        <span className="flex gap-2">
          <p className="font-semibold text-[#008000] text-md">{high}</p>
          <Image
            src={isGainer ? "/icons/up_arrow.svg" : "/icons/down_arrow.svg"}
            height={20}
            width={20}
            alt="arrow up"
          />
        </span>
      </div>
    </div>
  );
}
